# Generated by Django 6.0.2 on 2026-02-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=200)),
                ("subheadline", models.TextField()),
                (
                    "cta_text",
                    models.CharField(default="Start a project", max_length=100),
                ),
                ("cta_link", models.CharField(default="/contact", max_length=200)),
                (
                    "secondary_cta_text",
                    models.CharField(default="See products", max_length=100),
                ),
                (
                    "secondary_cta_link",
                    models.CharField(default="/products", max_length=200),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="content/hero/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(help_text="Lucide icon name", max_length=50)),
                ("features", models.JSONField(default=list)),
                ("technologies", models.JSONField(default=list)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="content/services/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Content",
                "verbose_name_plural": "Site Contents",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="content/team/"),
                ),
                ("linkedin", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("author", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="content/testimonials/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
