# Generated by Django 6.0.2 on 2026-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=1, max_digits=10)),
                (
                    "suffix",
                    models.CharField(
                        default="+", help_text="e.g., +, %, K", max_length=10
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Metric",
                "verbose_name_plural": "Metrics",
                "ordering": ["order"],
            },
        ),
    ]
